/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  content: ["./src/**/*.{js,jsx,ts,tsx,html,css}"],
  theme: {
    extend: {
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
      },
      colors: {
        'md-sys-color-primary': 'var(--md-sys-color-primary)',
        'md-sys-color-surface-tint': 'var(--md-sys-color-surface-tint)',
        'md-sys-color-on-primary': 'var(--md-sys-color-on-primary)',
        'md-sys-color-primary-container': 'var(--md-sys-color-primary-container)',
        'md-sys-color-on-primary-container': 'var(--md-sys-color-on-primary-container)',
        'md-sys-color-secondary': 'var(--md-sys-color-secondary)',
        'md-sys-color-on-secondary': 'var(--md-sys-color-on-secondary)',
        'md-sys-color-secondary-container': 'var(--md-sys-color-secondary-container)',
        'md-sys-color-on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        'md-sys-color-tertiary': 'var(--md-sys-color-tertiary)',
        'md-sys-color-on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'md-sys-color-tertiary-container': 'var(--md-sys-color-tertiary-container)',
        'md-sys-color-on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        'md-sys-color-error': 'var(--md-sys-color-error)',
        'md-sys-color-on-error': 'var(--md-sys-color-on-error)',
        'md-sys-color-error-container': 'var(--md-sys-color-error-container)',
        'md-sys-color-on-error-container': 'var(--md-sys-color-on-error-container)',
        'md-sys-color-background': 'var(--md-sys-color-background)',
        'md-sys-color-on-background': 'var(--md-sys-color-on-background)',
        'md-sys-color-surface': 'var(--md-sys-color-surface)',
        'md-sys-color-on-surface': 'var(--md-sys-color-on-surface)',
        'md-sys-color-surface-variant': 'var(--md-sys-color-surface-variant)',
        'md-sys-color-on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        'md-sys-color-outline': 'var(--md-sys-color-outline)',
        'md-sys-color-outline-variant': 'var(--md-sys-color-outline-variant)',
        'md-sys-color-shadow': 'var(--md-sys-color-shadow)',
        'md-sys-color-scrim': 'var(--md-sys-color-scrim)',
        'md-sys-color-inverse-surface': 'var(--md-sys-color-inverse-surface)',
        'md-sys-color-inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
        'md-sys-color-inverse-primary': 'var(--md-sys-color-inverse-primary)',
        'md-sys-color-primary-fixed': 'var(--md-sys-color-primary-fixed)',
        'md-sys-color-on-primary-fixed': 'var(--md-sys-color-on-primary-fixed)',
        'md-sys-color-primary-fixed-dim': 'var(--md-sys-color-primary-fixed-dim)',
        'md-sys-color-on-primary-fixed-variant': 'var(--md-sys-color-on-primary-fixed-variant)',
        'md-sys-color-secondary-fixed': 'var(--md-sys-color-secondary-fixed)',
        'md-sys-color-on-secondary-fixed': 'var(--md-sys-color-on-secondary-fixed)',
        'md-sys-color-secondary-fixed-dim': 'var(--md-sys-color-secondary-fixed-dim)',
        'md-sys-color-on-secondary-fixed-variant': 'var(--md-sys-color-on-secondary-fixed-variant)',
        'md-sys-color-tertiary-fixed': 'var(--md-sys-color-tertiary-fixed)',
        'md-sys-color-on-tertiary-fixed': 'var(--md-sys-color-on-tertiary-fixed)',
        'md-sys-color-tertiary-fixed-dim': 'var(--md-sys-color-tertiary-fixed-dim)',
        'md-sys-color-on-tertiary-fixed-variant': 'var(--md-sys-color-on-tertiary-fixed-variant)',
        'md-sys-color-surface-dim': 'var(--md-sys-color-surface-dim)',
        'md-sys-color-surface-bright': 'var(--md-sys-color-surface-bright)',
        'md-sys-color-surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'md-sys-color-surface-container-low': 'var(--md-sys-color-surface-container-low)',
        'md-sys-color-surface-container': 'var(--md-sys-color-surface-container)',
        'md-sys-color-surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'md-sys-color-surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
      },
    },
  },
  plugins: [],
}