FROM node:latest

RUN apt-get update && apt-get install -y default-jre
RUN java -version
RUN npm install -g firebase-tools

WORKDIR /app
COPY firebase/firebase.json .
COPY firebase/.firebaserc .
COPY firebase/firebase-firestore.rules .
COPY firebase/firebase-storage.rules .
RUN mkdir firebase-emulator-test-data

CMD ["firebase", "emulators:start", "--import", "firebase-emulator-test-data", "--export-on-exit", "firebase-emulator-test-data"]